# Generated by Django 3.1 on 2020-08-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(choices=[(1, 'worst'), (2, 'bad'), (3, 'Not bad'), (4, 'good'), (5, 'Excellent')]),
        ),
    ]
